// @ts-nocheck
// This file is auto-generated by ts_compile() - do not edit manually.
// Source: vit.R

import { Robj } from "rserve-ts";
import { z } from "zod";

/** Rserve may send length-0/1 character vectors as "" or a plain string. */
const zStringArray = () =>
  z
    .union([z.array(z.string()), z.string(), z.undefined()])
    .transform((val) => {
      if (val === undefined) return undefined
      if (Array.isArray(val)) return val
      if (val === '') return []
      return [val]
    })


export const samplingVariation = Robj.ocap(
  [
    z.union([
      Robj.js_function(
        [
          z.object({
            variables: zStringArray(),
            group_variables: zStringArray(),
            all_variables: zStringArray(),
            xvar: z.union([z.string(), z.undefined()]),
            yvar: z.union([z.string(), z.undefined()]),
            sample_size: z.union([z.number(), z.undefined()]),
            statistic: z.union([z.string(), z.undefined()]),
            status: z.union([z.string(), z.undefined()]),
            progress: z.union([z.number(), z.undefined()]),
            error_message: z.union([z.string(), z.undefined()]),
            population: z.union([z.instanceof(Float64Array), z.undefined()]),
            population_group: z.union([
              z.instanceof(Int32Array),
              z.undefined(),
            ]),
            group_levels: zStringArray(),
            group_stats: z.union([z.instanceof(Float64Array), z.undefined()]),
            stat_kind: z.union([z.string(), z.undefined()]),
            n_groups: z.union([z.number(), z.undefined()]),
            population_stat: z.union([z.number(), z.undefined()]),
            sample_stats: z.union([z.instanceof(Float64Array), z.undefined()]),
            sample_indices: z.union([z.instanceof(Int32Array), z.undefined()]),
            dist_y: z.union([z.instanceof(Float64Array), z.undefined()]),
            scales: z.union([
              z.object({
                pop: z.instanceof(Float64Array),
                sample: z.instanceof(Float64Array),
                dist: z.instanceof(Float64Array),
              }),
              z.undefined(),
            ]),
          }),
        ],
        z.null(),
      ),
      z.undefined(),
    ]),
  ],
  Robj.list({
    properties: Robj.list({
      variables: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([zStringArray()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(0)),
        set: Robj.ocap([zStringArray()], Robj.null()),
      }),
      group_variables: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([zStringArray()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(0)),
        set: Robj.ocap([zStringArray()], Robj.null()),
      }),
      all_variables: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([zStringArray()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(0)),
        set: Robj.ocap([zStringArray()], Robj.null()),
      }),
      xvar: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      yvar: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      sample_size: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.number()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.integer(1)),
        set: Robj.ocap([z.number()], Robj.null()),
      }),
      statistic: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      status: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      progress: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.number()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.integer(1)),
        set: Robj.ocap([z.number()], Robj.null()),
      }),
      error_message: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      population: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function([z.instanceof(Float64Array)], z.null()),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.numeric(0)),
        set: Robj.ocap([z.instanceof(Float64Array)], Robj.null()),
      }),
      population_group: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.instanceof(Int32Array)], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.integer(0)),
        set: Robj.ocap([z.instanceof(Int32Array)], Robj.null()),
      }),
      group_levels: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([zStringArray()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(0)),
        set: Robj.ocap([zStringArray()], Robj.null()),
      }),
      group_stats: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function([z.instanceof(Float64Array)], z.null()),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.numeric(0)),
        set: Robj.ocap([z.instanceof(Float64Array)], Robj.null()),
      }),
      stat_kind: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.string()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.character(1)),
        set: Robj.ocap([z.string()], Robj.null()),
      }),
      n_groups: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.number()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.integer(1)),
        set: Robj.ocap([z.number()], Robj.null()),
      }),
      population_stat: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.number()], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.numeric(1)),
        set: Robj.ocap([z.number()], Robj.null()),
      }),
      sample_stats: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function([z.instanceof(Float64Array)], z.null()),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.numeric(0)),
        set: Robj.ocap([z.instanceof(Float64Array)], Robj.null()),
      }),
      sample_indices: Robj.list({
        register: Robj.ocap(
          [Robj.js_function([z.instanceof(Int32Array)], z.null()), z.string()],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.integer(0)),
        set: Robj.ocap([z.instanceof(Int32Array)], Robj.null()),
      }),
      dist_y: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function([z.instanceof(Float64Array)], z.null()),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap([], Robj.numeric(0)),
        set: Robj.ocap([z.instanceof(Float64Array)], Robj.null()),
      }),
      scales: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function(
              [
                z.object({
                  pop: z.instanceof(Float64Array),
                  sample: z.instanceof(Float64Array),
                  dist: z.instanceof(Float64Array),
                }),
              ],
              z.null(),
            ),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap(
          [],
          Robj.list({
            pop: Robj.numeric(0),
            sample: Robj.numeric(0),
            dist: Robj.numeric(0),
          }),
        ),
        set: Robj.ocap(
          [
            z.object({
              pop: z.instanceof(Float64Array),
              sample: z.instanceof(Float64Array),
              dist: z.instanceof(Float64Array),
            }),
          ],
          Robj.null(),
        ),
      }),
    }),
    children: Robj.list(),
    capabilities: Robj.list({
      actions: Robj.list({
        enabled: Robj.logical(1),
        types: Robj.character(0),
        strict: Robj.character(1),
      }),
    }),
    methods: Robj.list({ record_choices: Robj.ocap([], Robj.null()) }),
  }),
);
export const vitWidget = Robj.ocap(
  [
    z.union([
      Robj.js_function(
        [
          z.object({
            dsInfo: z.union([
              z.object({ nrows: z.number(), ncols: z.number() }),
              z.undefined(),
            ]),
          }),
        ],
        z.null(),
      ),
      z.undefined(),
    ]),
  ],
  Robj.list({
    properties: Robj.list({
      dsInfo: Robj.list({
        register: Robj.ocap(
          [
            Robj.js_function(
              [z.object({ nrows: z.number(), ncols: z.number() })],
              z.null(),
            ),
            z.string(),
          ],
          Robj.character(1),
        ),
        get: Robj.ocap(
          [],
          Robj.list({ nrows: Robj.integer(1), ncols: Robj.integer(1) }),
        ),
        set: Robj.ocap(
          [z.object({ nrows: z.number(), ncols: z.number() })],
          Robj.null(),
        ),
      }),
    }),
    children: Robj.list({ samplingVariation: samplingVariation }),
    capabilities: Robj.list({
      actions: Robj.list({
        enabled: Robj.logical(1),
        types: Robj.character(0),
        strict: Robj.character(1),
      }),
    }),
    methods: Robj.list({ load_dataset: Robj.ocap([z.string()], Robj.null()) }),
  }),
);

export type TSamplingVariation = z.infer<typeof samplingVariation>;
export type TVitWidget = z.infer<typeof vitWidget>;

export const vitAppSchema = {
  vitWidget,
} satisfies z.ZodRawShape;

export type TVitApp = z.infer<z.ZodObject<typeof vitAppSchema, "strip">>;

export default vitAppSchema;
