// This file is auto-generated by ts_compile() - do not edit manually.
// Source: /home/tom/work/IAL/fellowship/ws1_tools/VIT/VIT-react/server/vit.R

import { Robj } from 'rserve-ts';
import { z } from 'zod';


export const list_modules = Robj.ocap([], Robj.character(0));
export const load_dataset = Robj.ocap([z.string()], Robj.character(0));


export type TList_modules = z.infer<typeof list_modules>;
export type TLoad_dataset = z.infer<typeof load_dataset>;


export const vitAppSchema = {
  list_modules,
  load_dataset
} satisfies z.ZodRawShape;

export type TVitApp = z.infer<z.ZodObject<typeof vitAppSchema, "strip">>;

export default vitAppSchema;
