# This file is auto-generated by ts_deploy() - do not edit manually.
# Source: vit.R

library(Rserve)
library(RserveTS)


source("modules/sampling_variation.R")

allModules <- c("samplingVariation")

vitWidget <- createWidget(
  name = "vitWidget",
  properties = list(
    data = "ANY",
    dsInfo = ts_list(
      nrows = ts_integer(1L, default = 0L),
      ncols = ts_integer(1L, default = 0L),
      default = list(nrows = 0L, ncols = 0L)
    ),
    samplingVariation = samplingVariation
    # module = "ANY"
  ),
  initialize = function(widget) {
    cli::cli_inform("Initializing VIT widget")
    # widget$module <- NULL
    NULL
  },
  methods = list(
    load_dataset = ts_function(
      function(url = ts_character(1)) {
        if (!requireNamespace("iNZightTools", quietly = TRUE)) {
          stop("Package 'iNZightTools' is required for smart_read()", call. = FALSE)
        }
        u <- as.character(url)
        d <- iNZightTools::smart_read(u)
        if (!is.data.frame(d)) {
          stop("smart_read() did not return a data.frame", call. = FALSE)
        }
        .self$data <- d
        .self$dsInfo$nrows <- nrow(d)
        .self$dsInfo$ncols <- ncol(d)

        num_cols <- names(d)[vapply(d, is.numeric, logical(1))]
        cat_cols <- categorical_column_names(d)
        child <- .self$samplingVariation
        child$vit <- .self
        child$set("variables", num_cols)
        child$set("group_variables", cat_cols)
        if (length(num_cols) > 0L) {
          child$set("xvar", num_cols[[1L]])
        } else {
          child$set("xvar", "")
        }
        if (length(cat_cols) > 0L) {
          child$set("yvar", cat_cols[[1L]])
        } else {
          child$set("yvar", "")
        }
        child$set("status", "idle")
        child$set("progress", 0L)
        reset_result_state(child)

        .self$updateState()
        child$updateState(all = TRUE)

        NULL
      },
      result = ts_null()
    )
    # samplingVariation = ts_function(
    #   function() {
    #     cli::cli_inform("Sampling Variation module selected")
    #     if (!is.null(.self$.module)) {
    #       cli::cli_inform("Destroying existing module")
    #       .self$.module$instance$destroy()
    #       .self$.module <- NULL
    #     }

    #     mod <- .self$create_dynamic_child(samplingVariation)
    #     cli::cli_inform("Creating new module")
    #     mod$instance$vit <- .self

    #     .self$.module <- mod
    #     cli::cli_inform("Updating state")
    #     .self$updateState()

    #     NULL
    #   },
    #   result = ts_null()
    # )
  ),
  export = TRUE
)
first.fns <- function() ts_app(list(
   vitWidget = vitWidget
))

oc.init <- function() Rserve:::ocap(first.fns)

Rserve::run.Rserve(
  websockets.port = 6311,
  websockets = TRUE,
  oob = TRUE,
  qap = FALSE,
  websockets.qap.oc = TRUE
)
