// This file is auto-generated by ts_compile() - do not edit manually.
// Source: vit.R

import { Robj } from 'rserve-ts';
import { z } from 'zod';


export const VitSession = Robj.ocap([z.union([Robj.js_function([z.object({ sceneJson: z.union([z.string(), z.undefined()]), gatingJson: z.union([z.string(), z.undefined()]), dataSummaryJson: z.union([z.string(), z.undefined()]), lastError: z.union([z.string(), z.undefined()]) })], z.null()), z.undefined()])], Robj.list({ properties: Robj.list({ sceneJson: Robj.list({ register: Robj.ocap([Robj.js_function([z.string()], z.null()), z.string()], Robj.character(1)), get: Robj.ocap([], Robj.character(1)), set: Robj.ocap([z.string()], Robj.null()) }), gatingJson: Robj.list({ register: Robj.ocap([Robj.js_function([z.string()], z.null()), z.string()], Robj.character(1)), get: Robj.ocap([], Robj.character(1)), set: Robj.ocap([z.string()], Robj.null()) }), dataSummaryJson: Robj.list({ register: Robj.ocap([Robj.js_function([z.string()], z.null()), z.string()], Robj.character(1)), get: Robj.ocap([], Robj.character(1)), set: Robj.ocap([z.string()], Robj.null()) }), lastError: Robj.list({ register: Robj.ocap([Robj.js_function([z.string()], z.null()), z.string()], Robj.character(1)), get: Robj.ocap([], Robj.character(1)), set: Robj.ocap([z.string()], Robj.null()) }) }), children: Robj.list(), capabilities: Robj.list({ actions: Robj.list({ enabled: Robj.logical(1), types: Robj.character(0), strict: Robj.character(1) }) }), methods: Robj.list({ loadCsv: Robj.ocap([z.string()], Robj.null()), setModule: Robj.ocap([z.string()], Robj.null()), setVarRoles: Robj.ocap([z.string(), z.string(), z.string()], Robj.null()), setStatConfig: Robj.ocap([z.string(), z.number()], Robj.null()), setBootstrapOptions: Robj.ocap([z.boolean(), z.boolean()], Robj.null()), recordAndBuild: Robj.ocap([], Robj.null()), resample: Robj.ocap([z.number()], Robj.null()), resampleBatch: Robj.ocap([z.number(), z.number()], Robj.null()) }) }));


export type TVitSession = z.infer<typeof VitSession>;


export const vitAppSchema = {
  VitSession
} satisfies z.ZodRawShape;

export type TVitApp = z.infer<z.ZodObject<typeof vitAppSchema, "strip">>;

export default vitAppSchema;
